---
title: "Figure5B"
author: "Anja Morgenthaler"
date: today
toc: true
format:
  html:
    number_sections: true
editor_options: 
  chunk_output_type: console
---

## Import Data

```{r}
library(readr)
df <- read.csv("/Users/anjam/Desktop/Miniproject/Data/processed/41698_2025_1043_MOESM3_ESM.csv")

#filter for only the variables we need

library(dplyr)

df <- df[, c("age", "smokingstatus", "group", "lungcancerscore")]
dfNOcontrol <- df[df$group != "control", ]
```

## cleaning data

```{r}
df$group <- ifelse(df$group =="lung cancer", 1, 0)
dfNOcontrol$group <- ifelse(dfNOcontrol$group =="lung cancer", 1, 0)

```

## fitting a model
```{r}
mod1 <- glm(group ~ lungcancerscore + age + smokingstatus, data = df, family = binomial)
mod2 <- glm(group ~ lungcancerscore + age + smokingstatus, data = dfNOcontrol, family = binomial)
```

## predicting 

```{r}
df$prob <- predict(mod1, type = "response")
dfNOcontrol$prob <- predict(mod2, type = "response")
```

## ROC curve first plot
```{r}
thresholds <- seq(0, 1, by = 0.01)

tpr <- numeric(length(thresholds))  # sensitivity
fpr <- numeric(length(thresholds))  # 1 - specificity
#values for first model
for (i in seq_along(thresholds)) {
  th <- thresholds[i]
  
  pred <- ifelse(df$prob >= th, 1, 0)
  
  TP <- sum(pred == 1 & df$group == 1)
  FP <- sum(pred == 1 & df$group == 0)
  TN <- sum(pred == 0 & df$group == 0)
  FN <- sum(pred == 0 & df$group == 1)
  
  tpr[i] <- TP / (TP + FN)
  fpr[i] <- FP / (FP + TN)
}
```

## ROC curve for the second model

```{r}
thresholds2 <- seq(0, 1, by = 0.01)

tpr2 <- numeric(length(thresholds2))  # sensitivity
fpr2 <- numeric(length(thresholds2))  # 1 - specificity
#values for first model
for (i in seq_along(thresholds2)) {
  th2 <- thresholds2[i]
  
  pred2 <- ifelse(dfNOcontrol$prob >= th2, 1, 0)
  
  TP2 <- sum(pred2 == 1 & dfNOcontrol$group == 1)
  FP2 <- sum(pred2 == 1 & dfNOcontrol$group == 0)
  TN2 <- sum(pred2 == 0 & dfNOcontrol$group == 0)
  FN2 <- sum(pred2 == 0 & dfNOcontrol$group == 1)
  
  tpr2[i] <- TP2 / (TP2 + FN2)
  fpr2[i] <- FP2 / (FP2 + TN2)
}
```


## Calculating the auc's
```{r}
auc <- sum(diff(fpr) * (head(tpr, -1) + tail(tpr, -1)) / 2)
auc2 <- sum(diff(fpr2) * (head(tpr2, -1) + tail(tpr2, -1)) / 2)
```


## plot
```{r}
plot(fpr, tpr, type = "l",
     xlab = "False Positive Rate",
     ylab = "True Positive Rate",
     main = "ROC Curve")

abline(0, 1, col = "blue", lty = 2)
lines(fpr2, tpr2, col = "red")

```

