---
title: "Reproducing figure 5a"
author: "Harchit Kaur"
date: today 
project: 
  output-dir: Output
  execute-dir: project
toc: true 
format: 
  html: 
    embed-resources: true
    number-sections: true
    code-fold: true
editor: visual 
editor_options: 
  chunk_output_type: console
execute:
  warning: false 
  message: false
  freeze: false 
---

## Prepare Session

```{r}
#| label: libraries and data import 
#| echo: false


library(ROCR)
#library(MetaIntegrator)
library(ggplot2)
library(parallel)
library(OptimalCutpoints)
library(data.table)
library(xgboost)
library(caret)
library(dplyr)
library(pROC)
library(e1071) #SVM
library(nnet) #MLP 
library(forcats)


df <- read.csv("Data/processed/41698_2025_1043_MOESM3_ESM.csv")

```

```{r}
#| label: clean dataset

# outcome
df$y_factor <- factor(ifelse(df$group == "lung cancer", "cancer", "noncancer"))

# smoking binary
df$smoking_binary <- ifelse(df$smokingstatus == "never", 0, 1)

# scale numeric variables (IMPORTANT for SVM/MLP)
df_scaled <- df
df_scaled$lungcancerscore <- scale(df$lungcancerscore)
df_scaled$age <- scale(df$age)

#compute AUC function 

get_auc <- function(pred, truth) {
  roc_obj <- roc(truth, pred)
  
  auc_val <- as.numeric(auc(roc_obj))
  ci_vals <- ci.auc(roc_obj)
  
  data.frame(
    auc = auc_val,
    lower_ci = ci_vals[1],
    upper_ci = ci_vals[3]
  )
}

#compute AUC function 

get_auc <- function(pred, truth) {
  roc_obj <- roc(truth, pred)
  
  auc_val <- as.numeric(auc(roc_obj))
  ci_vals <- ci.auc(roc_obj)
  
  data.frame(
    auc = auc_val,
    lower_ci = ci_vals[1],
    upper_ci = ci_vals[3]
  )
}
```

## Fit models

```{r}
#| label: cross validation

#use cross validation
control <- trainControl(
  method = "cv",
  number = 5,
  classProbs = TRUE,
  summaryFunction = twoClassSummary
)

#helper function
get_best_auc <- function(model, model_name, method_name) {
  best <- model$results[which.max(model$results$ROC), ]
  
  data.frame(
    model = model_name,
    method = method_name,
    auc = best$ROC,
    lower_ci = best$ROC - 1.96 * best$ROCSD,
    upper_ci = best$ROC + 1.96 * best$ROCSD
  )
}
```

```{r}
#| label: lr-models
lr_models <- list(
  "lung cancer score" = train(y_factor ~ lungcancerscore, df_scaled, method="glm", metric="ROC", trControl=control),
  "age" = train(y_factor ~ age, df_scaled, method="glm", metric="ROC", trControl=control),
  "smoking" = train(y_factor ~ smoking_binary, df_scaled, method="glm", metric="ROC", trControl=control),
  "age + smoking" = train(y_factor ~ age + smoking_binary, df_scaled, method="glm", metric="ROC", trControl=control),
  "lung cancer score + age + smoking" = train(y_factor ~ lungcancerscore + age + smoking_binary, df_scaled, method="glm", metric="ROC", trControl=control)
)

lr_results <- bind_rows(lapply(names(lr_models), function(name) {
  get_best_auc(lr_models[[name]], name, "logistic regression")
}))
```

```{r}
#| label: svm-models 

svm_models <- list("age + smoking" = train(y_factor ~ age + smoking_binary, df_scaled, method="svmRadial", metric="ROC", trControl=control),
  "lung cancer score + age + smoking" = train(y_factor ~ lungcancerscore + age + smoking_binary, df_scaled, method="svmRadial", metric="ROC", trControl=control)
)

svm_results <- bind_rows(lapply(names(svm_models), function(name) {
  get_best_auc(svm_models[[name]], name, "SVM")
}))
```

```{r}
#| label: MLP-models

mlp_models <- list("age + smoking" = train(y_factor ~ age + smoking_binary, df_scaled, method="nnet", metric="ROC", trControl=control, trace=FALSE),
  "lung cancer score + age + smoking" = train(y_factor ~ lungcancerscore + age + smoking_binary, df_scaled, method="nnet", metric="ROC", trControl=control, trace=FALSE)
)

mlp_results <- bind_rows(lapply(names(mlp_models), function(name) {
  get_best_auc(mlp_models[[name]], name, "MLP")
}))
```

```{r}
#| label: combine all results

# 1. combine results
results_all <- bind_rows(lr_results, svm_results, mlp_results)

# 2. set order
results_all$model <- factor(results_all$model, levels = c(
  "lung cancer score",
  "age",
  "smoking",
  "age + smoking",
  "lung cancer score + age + smoking"
))

levels = c(
  "lung cancer score",   # bottom
  "lung cancer score + age + smoking"  # top
)

# 3. split
single_models <- results_all %>%
  filter(model %in% c("lung cancer score", "age", "smoking"),
         method == "logistic regression")

multi_models <- results_all %>%
  filter(model %in% c("age + smoking", "lung cancer score + age + smoking"))

order_levels <- c(
  "smoking",
  "age",
  "lung cancer score",
  "age + smoking",
  "lung cancer score + age + smoking"
)

single_models$model <- factor(single_models$model, levels = order_levels)
multi_models$model  <- factor(multi_models$model,  levels = order_levels)

levels(results_all$model)
levels(single_models$model)
```

```{r}
# ggplot(results_all, aes(x = auc, y = model, color = method)) +
#   
#   geom_point(position = position_dodge(width = 0.3), size = 3) +
#   
#   geom_errorbarh(
#     aes(xmin = lower_ci, xmax = upper_ci),
#     position = position_dodge(width = 0.3),
#     height = 0.25,
#     size = 1
#   ) +
#   
#   geom_vline(xintercept = c(0.6, 0.7, 0.8, 0.9),
#              linetype = "dashed", color = "grey70") +
#   
#   scale_color_manual(values = c(
#     "logistic regression" = "black",
#     "SVM" = "#1f77b4",
#     "MLP" = "#9467bd"
#   )) +
#   
#   labs(
#     title = "AUC of lung cancer vs control/benign validation (UK)",
#     x = NULL,
#     y = NULL
#   ) +
#   
#   xlim(0.55, 0.9) +
#   
#   theme_minimal() +
#   
#   theme(
#     legend.position = "bottom",
#     axis.text.y = element_text(size = 12)
#   )
```

We can see that in full model the MLP is shifted towards left that is because we trained the model on the data set we have and not like in the paper. So the model is instable. It is not biological. Let me try to fix this.

```{r}
#| label: proper graph

# split data properly
single_models <- results_all %>%
  filter(model %in% c("lung cancer score", "age", "smoking"),
         method == "logistic regression")

multi_models <- results_all %>%
  filter(model %in% c("age + smoking", "lung cancer score + age + smoking"))

# plot
ggplot() +
  
  # SINGLE MODELS (NO DODGE → FIXES SMOKING CI)
  geom_point(
    data = single_models,
    aes(x = auc, y = model),
    color = "black",
    size = 3
  ) +
  
  geom_errorbarh(
    data = single_models,
    aes(xmin = lower_ci, xmax = upper_ci, y = model),
    height = 0.25,
    size = 1,
    color = "black"
  ) +
  
  # MULTI MODELS (WITH DODGE)
  geom_point(
    data = multi_models,
    aes(x = auc, y = model, color = method),
    position = position_dodge(width = 0.3),
    size = 3
  ) +
  
  geom_errorbarh(
    data = multi_models,
    aes(xmin = lower_ci, xmax = upper_ci, y = model, color = method),
    position = position_dodge(width = 0.3),
    height = 0.25,
    size = 1
  ) +
  
  geom_vline(xintercept = c(0.6, 0.7, 0.8, 0.9),
             linetype = "dashed", color = "grey70") +
  
  scale_color_manual(values = c(
    "logistics regression" = "black",
    "SVM" = "#1f77b4",
    "MLP" = "#9467bd"
  )) +
  
  labs(
    title = "AUC of lung cancer vs control/benign validation (UK)",
    x = NULL,
    y = NULL
  ) +
  
  coord_cartesian(xlim = c(0.55, 0.9)) +
  
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.y = element_text(size = 12)
  )
```

```{r}
#| label: AUC values
# in caret AUC are labbeled as ROCSens (Sensitivity)
#Sens --> (Sensitivity): True positive rate How well you detect cancer
#Spec --> (Specificity): True negative rate, How well you avoid false positives
model_svm$lr_models# -> test 3 different lr models - low C means simple value and vice verca
model_svm$results # -> test 3 different SVM models - low C means simple value and vice verca
model_mlp$results # -> test 3 different MLP models - low C means simple value and vice verca

results_all %>% filter(model == "smoking")
```
